### ISSUE TITLE
Version 2.0.0 in Platform IO does not contain the changes made to the library in GitHub

### ISSUE THREAD

**Issue by MaxMaeder** [adafruit/Adafruit_MLX90393_Library#14]
Hi

I am using this library in the Platform IO + VSCode development environment. I installed the latest version of the library using the PIO library system, which is 2.0.0, as it is here in GitHub. However, the `.h` and `.cpp` files do not contain the changes made to the library since the previous version. I verified the library version is in fact 2.0.0 by checking the `library.properties` file in PIO.

This issue strikes me as odd since I imagine you guys are using some sort of CI process to publish to PIO, but I would appreciate it if you would look into this.

Thanks again!

**Comment by ladyada** [comment]
hi @ivankravets please take a look at this question

**Comment by ivankravets** [comment]
Thanks for the reported issue. It has happened due to divergence between library.properties and the final release tag. You can track it here https://github.com/adafruit/Adafruit_MLX90393_Library/commit/9410e6fbfd73ac06d36a21f8689b81a4cf0f24b1

Normally, we bump manifest version BEFORE tagging a new release. In his case, there are a few commits between manifest's 2.0.0 and the final tag.

I recommend using [GitFlow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) to avoid this issue.

In any case, we manually re-imported this library. Should be fixed now.

**Comment by MaxMaeder** [comment]
Fixed. Thank you.

**Comment by ladyada** [comment]
@ivankravets hi there's no requirement for the Arduino IDE that the bumped properties is in the commit right before the tagged release. instead, the tagged release just has to be _after_ the property bump. please adjust platformio to match Arduino library manager's workflow or platformio will miss many other updates!

**Comment by ivankravets** [comment]
This is a legacy Arduino mode in our registry - it automatically scans libraries for updates depending on the manifest. We plan to remove it at all soon. We introduced in September a self-management service. Package authors publish their updates personally to the PlatformIO Registry. There are a few companies, such as Adafruit, where our legacy crawler does this work every 24h.

I think it makes sense to remove auto-updating from all adafruit libraries and keep them in the archive mode. We recommend people to use Arduino IDE for Adafruit products to avoid similar issues.

**Comment by ladyada** [comment]
yeah there is no way we would be able to keep up with personally publishing updates to the registry, we have hundreds of libraries (600-700 now, python and arduino), with 10+ releases a week. if platformio adds an Actions CI script we can add to our workflow (every library uses Actions!) for automatic notification!
